version: '2'
services:
  php7:
    container_name: php7
    build: ./php
    volumes:
      - /path/to/your/config/php:/usr/local/etc/php
      - /path/to/your/code/myapp:/var/www/html/myapp
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:1.15.2
    ports:
      - 8080:80
    volumes:
      - /path/to/your/config/nginx:/etc/nginx/conf.d
      - /path/to/your/code/myapp:/var/www/html/myapp
      - /path/to/your/logs:/var/log/nginx
    depends_on:
      - php7

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /path/to/your/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
